# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build to githubpages CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
    - name: install dependencies
      run: npm i
    - name: build
      run: npm run build
    - name: git config
      run: |
        cd dist
        git config --global user.email Actions@github.com
        git config --global user.name Actions
        git init
        git add -A
        git commit -m "github action auto build"
        git push -f origin HEAD:gh-pages
